
services:

  # NODO MASTER DI HADOOP
  namenode:
    image: aci-hadoop:3.4.1-namenode
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=CLSTHADOOP
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870" # interfaccia web del namenode
      - "9000:9000"
    volumes:
      - vol_hadoop_namemode:/hadoop/dfs/name
    networks:
      - net-cloudera

  # DATA NODE 1 CLUSTER HADOOP
  datanode1:
    image: aci-hadoop:3.4.1-datanode
    container_name: datanode1
    hostname: datanode1
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop.env
    ports:
      - "9864:9864"
    volumes:
      - vol_hadoop_datanode1:/hadoop/dfs/data
    networks:
      - net-cloudera  

  # DATA NODE 2 CLUSTER HADOOP
  datanode2:
    image: aci-hadoop:3.4.1-datanode
    container_name: datanode2
    hostname: datanode2
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop.env
    ports:
      - "9865:9864"
    volumes:
      - vol_hadoop_datanode2:/hadoop/dfs/data
    networks:
      - net-cloudera  

  # DATA NODE 3 CLUSTER HADOOP
  datanode3:
    image: aci-hadoop:3.4.1-datanode
    container_name: datanode3
    hostname: datanode3
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop.env
    ports:
      - "9866:9864"
    volumes:
      - vol_hadoop_datanode3:/hadoop/dfs/data
    networks:
      - net-cloudera  

  # YARN: RESOURCE MANAGER (MASTER)
  resourcemanager:
    image: aci-hadoop:3.4.1-resourcemanager
    container_name: resourcemanager
    hostname: resourcemanager
    environment:             
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864
    env_file:
      - ./hadoop.env
    ports:
      - "8088:8088"
      - "19888:19888"
    networks:
      - net-cloudera 

  httpfs:
    image: aci-hadoop:3.4.1-httpfs
    container_name: httpfs
    hostname: httpfs
    environment:             
      - CLUSTER_NAME=CLSTHADOOP
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864
    env_file:
      - ./hadoop.env
    ports:
      - "14000:14000"
    networks:
      - net-cloudera

  # YARN: NODE MANAGER 1
  nodemanager1:
    image: aci-hadoop:3.4.1-nodemanager
    container_name: nodemanager1
    hostname: nodemanager1
    environment:             
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088
    env_file:
      - ./hadoop.env
    networks:
      - net-cloudera 

  # YARN: NODE MANAGER 2
  nodemanager2:
    image: aci-hadoop:3.4.1-nodemanager
    container_name: nodemanager2
    hostname: nodemanager2
    environment:
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088
    env_file:
      - ./hadoop.env
    networks:
      - net-cloudera 

  # YARN: HISTORY SERVER
  historyserver:
    image: aci-hadoop:3.4.1-historyserver
    container_name: historyserver
    hostname: historyserver
    environment:
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088
    env_file:
      - ./hadoop.env
    ports:
      - "8188:8188"
      - "19889:19888"
    volumes:
      - vol_hadoop_historyserver:/hadoop/yarn/timeline
    networks:
      - net-cloudera  

  # HBASE: ZOOKEPER
  hbasezk:
    image: aci-hbase:2.5.11-zookeeper
    container_name: hbasezk
    hostname: hbasezk
    ports:
      - "2181:2181"
    depends_on:
      - namenode
    networks:
      - net-cloudera  
    volumes:
      - ./config/hbase-site.xml:/opt/hbase/conf/hbase-site.xml  
      - ./config/regionservers:/opt/hbase/conf/regionservers  

  # HBASE: MASTER
  hbasemaster:
    image: aci-hbase:2.5.11-master
    container_name: hbasemaster
    hostname: hbasemaster
    ports:
      - "16010:16010"
    depends_on:
      - namenode
      - hbasezk
    networks:
      - net-cloudera
    volumes:
      - ./config/hbase-site.xml:/opt/hbase/conf/hbase-site.xml  
      - ./config/regionservers:/opt/hbase/conf/regionservers  

  # HBASE: REGION SERVER 1
  hbaseregion1:
    image: aci-hbase:2.5.11-regionserver
    container_name: hbaseregion1
    hostname: hbaseregion1
    depends_on:
      - hbasemaster
      - hbasezk
    networks:
      - net-cloudera
    volumes:
      - ./config/hbase-site.xml:/opt/hbase/conf/hbase-site.xml  
      - ./config/regionservers:/opt/hbase/conf/regionservers  

  # HBASE: REGION SERVER 2
  hbaseregion2:
    image: aci-hbase:2.5.11-regionserver
    container_name: hbaseregion2
    hostname: hbaseregion2
    depends_on:
      - hbasemaster
      - hbasezk
    networks:
      - net-cloudera
    volumes:
      - ./config/hbase-site.xml:/opt/hbase/conf/hbase-site.xml  
      - ./config/regionservers:/opt/hbase/conf/regionservers  

  # HBASE: REGION SERVER 3
  hbaseregion3:
    image: aci-hbase:2.5.11-regionserver
    container_name: hbaseregion3
    hostname: hbaseregion3
    depends_on:
      - hbasemaster
      - hbasezk
    networks:
      - net-cloudera
    volumes:
      - ./config/hbase-site.xml:/opt/hbase/conf/hbase-site.xml  
      - ./config/regionservers:/opt/hbase/conf/regionservers  

  # HUE: WEB APP
  hue:
    image: gethue/hue:latest
    container_name: hue
    hostname: hue
    ports:
      - "8888:8888"
    networks:
      - net-cloudera
    depends_on:
      - namenode
      - datanode1
      - resourcemanager
      - historyserver
#    environment:
#      HUE_HADOOP_HDFS_PORT: 9000
#      HUE_HADOOP_MR_HISTORY_SERVER: historyserver:10020
#      HUE_HADOOP_YARN_RESOURCE_MANAGER: resourcemanager:8032
#      HUE_HADOOP_YARN_PROXY_API_URL: resourcemanager:8088
#      HUE_HADOOP_YARN_HISTORY_SERVER_URL: historyserver:19888
#      HUE_HADOOP_HDFS_WEBHDFS_URL: http://namenode:9870/webhdfs/v1
    volumes:
      - ./hue.ini:/usr/share/hue/desktop/conf/hue.ini
    #  - ./conf:/etc/hbase/conf
   

  hive-mt-db:
    image: postgres:13
    container_name: hive-mt-postgres
    hostname: hive-mt-postgres
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - "5432:5432"
    networks:
      - net-cloudera
    volumes:
      - vol_mt_postgres:/var/lib/postgresql/data
 
  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    hostname: hive-metastore
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - SERVICE_OPTS="-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password"
      - HIVE_METASTORE_DATABASE_TYPE=postgres
      - HIVE_METASTORE_POSTGRES_HOST=hive-mt-postgres
      - HIVE_METASTORE_POSTGRES_PORT=5432
      - HIVE_METASTORE_POSTGRES_DB=metastore
      - HIVE_METASTORE_POSTGRES_USER=hive
      - HIVE_METASTORE_POSTGRES_PASSWORD=hive
    ports:
      - "9083:9083"
    networks:
      - net-cloudera



volumes:
  vol_mt_postgres:
    driver: local
  vol_hadoop_namemode:
    driver: local
  vol_hadoop_datanode1:
    driver: local
  vol_hadoop_datanode2:
    driver: local
  vol_hadoop_datanode3:
    driver: local
  vol_hadoop_historyserver:
    driver: local
  vol_hue:
    driver: local

networks:
  net-cloudera:
    name: net-cloudera
    driver: bridge